package synchronization;

class Bracketsss {
	synchronized static  public void generate(String ThredCode) {
		for (int i = 1; i <= 10; i++) {
			if (i <= 5) {
				System.out.print("[");
			} else {
				System.out.print("]");
			}
		}
		System.out.println("Generated By Thread: " + ThredCode);
	}
}

public class StaticThread {
	public static void main(String[] args) {

		new Thread(new Runnable() {

			@Override
			public void run() {
				for (int i = 1; i <= 5; i++) {
					Bracketsss.generate("Thread1");
				}

			}
		}).start();
		new Thread(new Runnable() {

			@Override
			public void run() {
				for (int i = 1; i <= 5; i++) {
					Bracketsss.generate("Thread2");
				}

			}
		}).start();
	}

}
